version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
        environment:
          RACK_ENV: CI
    working_directory: ~/service
    steps:
      - checkout
      - setup_docker_engine
      - run: |
          set -ex
          curl -L -o /tmp/docker-1.13.1.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.13.1.tgz
          tar -xz -C /tmp -f /tmp/docker-1.13.1.tgz
          mv /tmp/docker/* /usr/bin

      - run: |
          TAG=$(git describe --tags)
          docker build -t dtr.getdropstream.com/$DOCKER_USER/service_with_hooks:$TAG .
          docker tag dtr.getdropstream.com/$DOCKER_USER/service_with_hooks:$TAG dtr.getdropstream.com/$DOCKER_USER/service_with_hooks:latest
          docker login -u $DOCKER_USER -p $DOCKER_PASS dtr.getdropstream.com
          docker push dtr.getdropstream.com/$DOCKER_USER/service_with_hooks:$TAG
          
